import type { CardDefinition } from '../types'

export const CARD_CATALOG: CardDefinition[] = [
  {
    id: 'carte1',
    color: 'red',
    points: 5,
    title_fr: 'Agent Multilingue',
    title_en: 'Multilingual Agent',
    mission_fr: "Votre agent doit repondre automatiquement dans la langue de la question : francais si en francais, anglais si en anglais. Ajoutez l'instruction dans les Instructions systeme et testez avec les deux langues.",
    mission_en: 'Your agent must automatically respond in the language of the question. Add the instruction in system Instructions and test with both languages.',
  },
  {
    id: 'carte2',
    color: 'red',
    points: 5,
    title_fr: 'Reponse Structuree',
    title_en: 'Structured Response',
    mission_fr: "Chaque reponse doit suivre : Resume (1 phrase), Details (liste), Recommandation. Ajoutez l'instruction et testez.",
    mission_en: 'Every response must follow: Summary (1 sentence), Details (list), Recommendation. Add the instruction and test.',
  },
  {
    id: 'carte3',
    color: 'red',
    points: 5,
    title_fr: "Gestion d'Erreur",
    title_en: 'Error Handling',
    mission_fr: "Votre agent doit detecter et gerer elegamment les questions hors perimetre. Testez avec 3 questions hors-sujet imposees.",
    mission_en: 'Your agent must detect and gracefully handle out-of-scope questions. Test with 3 imposed off-topic questions.',
  },
  {
    id: 'carte4',
    color: 'red',
    points: 5,
    title_fr: 'Agent Expert Metier',
    title_en: 'Business Expert Agent',
    mission_fr: "Transformez l'agent en expert technique Use Case X avec un role precis, un ton expert, des citations de sources et des escalades appropriees.",
    mission_en: 'Transform the agent into a Use Case X technical expert with a precise role, expert tone, source citations, and appropriate escalations.',
  },
  {
    id: 'carte5',
    color: 'orange',
    points: 3,
    title_fr: 'Source de Connaissance',
    title_en: 'Knowledge Source',
    mission_fr: "Ajoutez une nouvelle source de connaissance (document, page web ou fichier interne). Test: posez une question issue du document.",
    mission_en: 'Add a new knowledge source (document, webpage, or internal file). Test: ask a question from the document.',
  },
  {
    id: 'carte6',
    color: 'orange',
    points: 3,
    title_fr: 'Question Piege Interequipes',
    title_en: 'Cross-Team Trick Question',
    mission_fr: "Une equipe adverse pose une question complexe a votre agent. La question doit comporter au moins 2 conditions ou sous-questions.",
    mission_en: 'An opposing team asks a complex question to your agent. The question must include at least 2 conditions or sub-questions.',
  },
  {
    id: 'carte7',
    color: 'orange',
    points: 3,
    title_fr: 'Prompt Ameliore',
    title_en: 'Improved Prompt',
    mission_fr: "Reecrivez les instructions systeme pour reduire les hallucinations avec des grounding instructions. Testez avec un produit fictif.",
    mission_en: 'Rewrite system instructions to reduce hallucinations with grounding instructions. Test with a fictional product.',
  },
  {
    id: 'carte8',
    color: 'orange',
    points: 3,
    title_fr: 'Agent Pedagogique',
    title_en: 'Educational Agent',
    mission_fr: "Votre agent doit expliquer Copilot Studio a un debutant complet en 4 etapes simples, avec analogies, sans jargon.",
    mission_en: 'Your agent must explain Copilot Studio to a complete beginner in 4 simple steps, with analogies, no jargon.',
  },
  {
    id: 'carte9',
    color: 'green',
    points: 1,
    title_fr: "Personnalite de l'Agent",
    title_en: 'Agent Personality',
    mission_fr: "Donnez a votre agent une personnalite : nom, ton, signature en fin de reponse, et un easter egg sur \"Qui es-tu ?\".",
    mission_en: 'Give your agent a personality: name, tone, signature at end of response, and an easter egg for "Who are you?".',
  },
  {
    id: 'carte10',
    color: 'green',
    points: 1,
    title_fr: 'Question Inattendue du Facilitateur',
    title_en: "Facilitator's Unexpected Question",
    mission_fr: "Le facilitateur pose une question tiree aleatoirement d'un document connecte. L'agent doit repondre correctement avec citation.",
    mission_en: 'The facilitator asks a random question from a connected document. The agent must answer correctly with citation.',
  },
  {
    id: 'carte11',
    color: 'green',
    points: 1,
    title_fr: 'Reponse Courte',
    title_en: 'Short Answer',
    mission_fr: "Ajoutez une contrainte : reponses de 3 phrases max pour les questions simples. Developpez seulement si demande.",
    mission_en: 'Add a constraint: 3 sentence max for simple questions. Expand only if asked.',
  },
  {
    id: 'carte12',
    color: 'green',
    points: 1,
    title_fr: 'Exemple Concret Obligatoire',
    title_en: 'Mandatory Concrete Example',
    mission_fr: "Chaque reponse doit inclure un exemple concret avec un produit Use Case X. Testez avec une question sur la garantie.",
    mission_en: 'Every response must include a concrete example with a Use Case X product. Test with a warranty question.',
  },
  {
    id: 'joker',
    color: 'purple',
    points: 2,
    title_fr: 'Joker',
    title_en: 'Joker',
    mission_fr: "Choix A : Volez 2 points a l'equipe de votre choix (+2 pour vous, -2 pour eux). Choix B : Obtenez 1 indice du facilitateur (30 sec max).",
    mission_en: 'Choice A: Steal 2 points from any team (+2 for you, -2 for them). Choice B: Get 1 hint from facilitator (30 sec max).',
  },
  {
    id: 'speedrun',
    color: 'purple',
    points: 2,
    title_fr: 'Speed Run',
    title_en: 'Speed Run',
    mission_fr: "5 minutes chrono pour ameliorer votre agent. L'amelioration doit etre visible et testable. +2 si complete dans le temps.",
    mission_en: '5-minute sprint to improve your agent. The improvement must be visible and testable. +2 if completed in time.',
  },
  {
    id: 'pitch',
    color: 'purple',
    points: 3,
    title_fr: 'Pitch',
    title_en: 'Pitch',
    mission_fr: "Presentez votre agent en 60 secondes : probleme (15s), demo live (25s), impact business (20s). Entre 45-60s = +3 pts.",
    mission_en: 'Present your agent in 60 seconds: problem (15s), live demo (25s), business impact (20s). Between 45-60s = +3 pts.',
  },
]

export function getCardById(id: string): CardDefinition | undefined {
  return CARD_CATALOG.find((c) => c.id === id)
}

export function getCardsByColor(color: CardDefinition['color']): CardDefinition[] {
  return CARD_CATALOG.filter((c) => c.color === color)
}
